name: dapp_personal_wallet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.3
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  http: ^0.13.0
  shared_preferences: ^2.0.11
  web3dart: ^2.0.0
  web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/contracts_abis/Investment.json
    - assets/images/
    - .env
